schema_version: 1

context:
  name: tritonclient
  version: "2.62.0"

recipe:
  name: ${{ name|lower }}-split
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/t/tritonclient/tritonclient-${{ version }}-py3-none-any.whl
  sha256: c64dd3e905ff9688fa9871c6245273ab81ecde42f281f43bc5e31f84c094a4cf

build:
  number: 0

outputs:
  - package:
      name: ${{ name }}
    build:
      noarch: python
      script:
        file: build_base.sh
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - unzip
      run:
        - python >=${{ python_min }}
        - numpy >=1.19.1,<2
        - python-rapidjson >=0.9.1
        - urllib3 >=2.0.7
    tests:
      - python:
          imports:
            - tritonclient
            - tritonclient.utils
          pip_check: true
          python_version: ${{ python_min }}.*
  - package:
      name: ${{ name }}-http
    build:
      noarch: python
      script:
        - unzip tritonclient-*.whl
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - unzip
        - ${{ pin_subpackage('tritonclient', exact=True) }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('tritonclient', exact=True) }}
        - aiohttp >=3.8.1,<4.0.0
        - geventhttpclient >=2.3.3
    tests:
      - python:
          imports:
            - tritonclient.http
          pip_check: true
          python_version: ${{ python_min }}.*
  - package:
      name: ${{ name }}-grpc
    build:
      noarch: python
      script:
        - unzip tritonclient-*.whl
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - unzip
        - ${{ pin_subpackage('tritonclient', exact=True) }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('tritonclient', exact=True) }}
        - grpcio >=1.63.0,<1.68
        - packaging >=14.1
        - protobuf >=5.26.1,<6.0dev
    tests:
      - python:
          imports:
            - tritonclient.grpc
          pip_check: true
          python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: tritonclient-${{ version }}.dist-info/LICENSE.txt
  summary: Python client library and utilities for communicating with Triton Inference Server.
  homepage: https://developer.nvidia.com/nvidia-triton-inference-server

extra:
  recipe-maintainers:
    - janjagusch
    - ivergara
    - nick-harmening
