schema_version: 1

context:
  name: tritonclient
  version: 2.49.0

recipe:
  name: ${{ name|lower }}-split
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/t/tritonclient/tritonclient-${{ version }}-py3-none-any.whl
  sha256: 8715c8f82061e9e2d85242c903e72e68c070c6845c0334fa88fc9f44a1904e77

build:
  number: 1

outputs:
  - package:
      name: ${{ name }}
    build:
      noarch: python
      script:
        file: build_base.sh
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools
      run:
        - python >=${{ python_min }}
        - numpy<2,>=1.19.1
        - python-rapidjson>=0.9.1
        - urllib3>=2.0.7
    tests:
      - python:
          imports:
            - tritonclient
            - tritonclient.utils
          pip_check: true
          python_version: ${{ python_min }}.*
  - package:
      name: ${{ name }}-http
    build:
      noarch: python
      script:
      - unzip tritonclient-*.whl
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - ${{ pin_subpackage('tritonclient', exact=True) }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('tritonclient', exact=True) }}
        - geventhttpclient>=1.4.4,<=2.0.2
        - aiohttp>=3.8.1,<4.0.0
    tests:
      - python:
          imports:
            - tritonclient.http
          pip_check: true
          python_version: ${{ python_min }}.*
  - package:
      name: ${{ name }}-grpc
    build:
      noarch: python
      script:
      - unzip tritonclient-*.whl
    requirements:
      host:
        - python ${{ python_min }}.*
        - pip
        - setuptools
        - ${{ pin_subpackage('tritonclient', exact=True) }}
      run:
        - python >=${{ python_min }}
        - ${{ pin_subpackage('tritonclient', exact=True) }}
        - grpcio>=1.41.0
        - protobuf>=3.5.0,<4
        - packaging>=14.1
    tests:
      - python:
          imports:
            - tritonclient.grpc
          pip_check: true
          python_version: ${{ python_min }}.*

about:
  license: BSD-3-Clause
  license_file: tritonclient-${{ version }}.dist-info/LICENSE.txt
  summary: Python client library and utilities for communicating with Triton Inference Server.
  homepage: https://developer.nvidia.com/nvidia-triton-inference-server

extra:
  recipe-maintainers:
    - janjagusch
    - ivergara
    - nick-harmening
